databases:
  - name: BudgetMate-New-Database
    databaseName: budgetmate_new_database
    user: budgetmate_new_database_user

services:
  - type: web
    name: sazzad
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetmate_new_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false